# Generated by Django 3.2.25 on 2024-04-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
