# Generated by Django 3.2.25 on 2024-04-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Patient_Id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
